let home = document.querySelector("#home");
let home_trigger = document.querySelector("#home_trigger");
let apps = document.querySelector("#apps");
let apps_svg = document.querySelector("#apps_svg");
let apps_trigger = document.querySelector("#apps_trigger");
let games = document.querySelector("#games");
let games_svg = document.querySelector("#games_svg");
let games_trigger = document.querySelector("#games_trigger");
let library = document.querySelector("#library");
let library_trigger = document.querySelector("#library_trigger");
let library_svg = document.querySelector("#library_svg");
let help = document.querySelector("#help");
let help_trigger = document.querySelector("#help_trigger");
let help_svg = document.querySelector("#help_svg");
home_trigger.onclick = function(){
  home.style.opacity = "1";
  home_trigger.style.background = "#afafaf44";
  help_trigger.style.background = "transparent";
  library_trigger.style.background = "transparent";
  games_trigger.style.background = "transparent";
  apps_trigger.style.background = "transparent";
  library.style.opacity="0";
  apps.style.opacity="0";
  games.style.opacity="0";
  help.style.opacity="0"
  help_svg.style.fill="#000"
  games_svg.style.fill="#000";
  apps_svg.style.fill="#000";
  library_svg.style.fill="#000";
}
apps_trigger.onclick = function () {
  apps.style.opacity="1";
  apps_trigger.style.background = "#afafaf44";
  help_trigger.style.background = "transparent";
  library_trigger.style.background = "transparent";
}
  games_trigger.style.background = "transparent";
  home_trigger.style.background = "transparent"
  library.style.opacity="0";
  home.style.opacity = "0";
  help.style.opacity="0"
  help_svg.style.fill="#000"
  games.style.opacity="0";
  apps_svg.style.fill="#007efb";
  games_svg.style.fill="#000";
  library_svg.style.fill="#000";
}
games_trigger.onclick = function () {
  games.style.opacity="1";
  library.style.opacity="0";
  apps.style.opacity="0";
  help.style.opacity="0"
  games_trigger.style.background = "#afafaf44";
  help_trigger.style.background = "transparent";
  library_trigger.style.background = "transparent";
  apps_trigger.style.background = "transparent";
  home_trigger.style.background = "transparent"
  help_svg.style.fill="#000"
  home.style.opacity = "0";
  games_svg.style.fill="#007efb";
  apps_svg.style.fill="#000";
  library_svg.style.fill="#000";
}
library_trigger.onclick = function () {
  games.style.opacity="0";
  library.style.opacity="1";
  apps.style.opacity="0";
  home.style.opacity = "0";
  library_trigger.style.background = "#afafaf44";
  help_trigger.style.background = "transparent";
  games_trigger.style.background = "transparent";
  apps_trigger.style.background = "transparent";
  home_trigger.style.background = "transparent"
  help.style.opacity="0"
  help_svg.style.fill="#000"
  games_svg.style.fill="#000";
  apps_svg.style.fill="#000";
  library_svg.style.fill="#007efb";
}
help_trigger.onclick = function () {
  games.style.opacity="0";
  help.style.opacity="1"
  library.style.opacity="0";
  apps.style.opacity="0";
  home.style.opacity = "0";
  help_trigger.style.background = "#afafaf44";
  library_trigger.style.background = "transparent";
  games_trigger.style.background = "transparent";
  apps_trigger.style.background = "transparent";
  home_trigger.style.background = "transparent"
  games_svg.style.fill="#000";
  apps_svg.style.fill="#000";
  library_svg.style.fill="#000";
  help_svg.style.fill="#007efb"
}
